version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: habituser
      POSTGRES_PASSWORD: habitpass
      POSTGRES_DB: habitdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
